num_non_zero := "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
num_with_zero := "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
num := num_non_zero (num_with_zero)*

expr := equality
equality := relational ("==" relational | "!=" relational)*
relational := add ("<" add | "<=" add | ">" add | ">=" add)*
add := mul ("+" mul | "-" mul)*
mul := num ("*" num | "/" num)*
primary := num | "(" expr ")"
